### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [govindtkedar/percentile-rank#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by govindtkedar** [comment]
Thanks for your consideration. Please let me know what details you would need from me for your help.

**Comment by geopic** [comment]
Excellent, I'll start soon. I'll let you know if I need anything.
